GET http://localhost:3000/login/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFpbGV5IiwiaWF0IjoxNzQ3OTUxNzQwfQ.yQd9_LX1sjf_mt0FEtHCK0gSL8AMcMP_HA1hL6PRdBk

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFpbGV5IiwiaWF0IjoxNzQ3OTM2ODkzfQ.CLZvgNQS6rwoQwDK04YZ6FJq44taqvABDZicsX9iHjs"
}

###

GET http://localhost:3000/signup

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "test",
    "username": "test",
    "email": "test@gmail.com",
    "password": "test"
}
