GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFpbGV5IiwiaWF0IjoxNzQ3OTU4MDYwLCJleHAiOjE3NDc5NTgwODB9.O86948-Pb2Isun8togfrPuuHuENjLxJhR2rwTu3L55Y

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFpbGV5IiwiaWF0IjoxNzQ3OTU4MDE4fQ.SF9HX4ftieMUSp-REtZ2WpEd3sb9EQmYlfz8IFT6gdg"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Bailey"
}
